### ISSUE TITLE
Does this support redmine version 4.0.1-1

### ISSUE THREAD

**Issue by ram3772340** [dro123/redmine_meeting_room_calendar#50]
Getting a below error when running rake in the remine version 4.0+.

![image](https://user-images.githubusercontent.com/19993793/54536161-1187c080-4988-11e9-953f-f8a12ed532ab.png)

Any thoughts?

**Comment by dro123** [comment]
Probably the same solution as this one:
https://github.com/ruby-grape/grape/issues/1666#issuecomment-318083431

**Comment by aceccarelli** [comment]
Hi!
For me this solution didn't work
After update file init.rb in line 34 I did get a below error 
If you can help me, I will be very grateful, as it is a plugin that I use a lot and is locking up to migrate to version 4.1

Thnaks!

<pre>
redmine@Redmine:/var/www/redmine-4.1.0/plugins/redmine_meeting_room_calendar$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /var/www/redmine-4.1.0)
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/var/www/redmine-4.1.0/plugins/redmine_meeting_room_calendar/init.rb:34:in `<top (required)>'
/var/www/redmine-4.1.0/lib/redmine/plugin.rb:181:in `block in load'
/var/www/redmine-4.1.0/lib/redmine/plugin.rb:172:in `each'
/var/www/redmine-4.1.0/lib/redmine/plugin.rb:172:in `load'
/var/www/redmine-4.1.0/config/initializers/30-redmine.rb:20:in `<top (required)>'
/var/www/redmine-4.1.0/config/environment.rb:16:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
</pre>

**Comment by VVD** [comment]
@dro123, can you, please, update this plugin to support Redmine 4.x (4.0, 4.1, future 4.2)?

**Comment by dro123** [comment]
I merged this:
https://github.com/dro123/redmine_meeting_room_calendar/pull/51
Try if it helps.
I don't have the development environment anymore to test this since I'm currently not using redmine anywhere.
